### ISSUE TITLE
Add prepend_data and prependtoblock

### ISSUE THREAD

**Issue by mitar** [ojii/django-sekizai#33]
Sometimes it is useful to have more control where in the order you want a script or css file to be added. I would propose simple `prepend_data` and `prependtoblock` tags, which are very similar to existing tags, only they call `context[varname][key].insert(0, value)` and `context[varname][name].insert(0, rendered_contents)`.

**Comment by ojii** [comment]
closing this as it's old, has not resulted in a mergable pull request and I'm somewhat opposed to the idea. If there's still a big need for this, re-open and explain.
