### ISSUE TITLE
libsass integration

### ISSUE THREAD

**Issue by jrief** [ojii/django-sekizai#40]
This issue is to continue to evaluate strategies for integrating **libsass** into the workflow with **django-sekizai** as discussed in https://github.com/divio/django-cms/issues/3600.

Since it seems as if there is no satisfying solution to do offline compression for files managed by Sekizai, one would have to install **libsass** on every production environment. This is not what we want.

Therefore I'd like to discuss a different approach. Instead of doing the compilation from *.scss to *.css, when the template engine "sees" this tag
``{% render_block "css" postprocessor "compressor.contrib.sekizai.compress" %}``
how about doing the compilation when  the template engine "sees" this tag
``{% addtoblock "css" %}<link href="{{ STATIC_URL }}css/my-style.scss" rel="stylesheet" type="text/x-scss" />{% endaddtoblock %}``?

Then an auto generated file named, say ``<some-dir>/my-style-<somehashvalue>.css``, could be added somewhere the the project's static (auto-generated) folder and delivered via PyPI.

Now, whenever Django is configured for production and Sekizai sees the tag ``addtoblock``, then internally the file path is converted to the css file expected inside the auto-generated folder, but without compilation. 

Do you think this is a feasible solution?

For details how libsass can be integrated with Sekizai and django-compressor, refer to this document: https://groups.google.com/forum/#!topic/django-cms/KO7K1iMIjmo

**Comment by ojii** [comment]
Would a thing like ``postprocessor <path>`` for ``addtoblock`` solve this? That postprocessor could translate the paths.

**Comment by jrief** [comment]
Yes, that's exactly the thing I was thinking about.
However, I would name it preprocessor, but that's a question of taste.

Something else to consider: How shall the mapping rule be defined?
We could write
``{% addtoblock "css" %}<link href="{% static %}css/my-style.scss" rel="stylesheet" type="text/x-scss" />{% endaddtoblock %}``
and use ``text/x-scss`` as the key for applying a rule, or we could write
 ``{% addtoblock "scss" %}<link href="{% static %}css/my-style.scss" rel="stylesheet" type="text/css" />{% endaddtoblock %}``
and use ``scss`` as the key for applying a rule.

One of the advantages I see using the latter proposal, is to convert files found in directory ``bower_compontents`` directly into the Google's CDN counterpart. Today, I used the package https://github.com/sindresorhus/gulp-google-cdn and it does a perfect job. This means that with Sekizai, then we could convert external dependencies managed by bower from a local include to a CDN include.

**Comment by ojii** [comment]
> Yes, that's exactly the thing I was thinking about.
> However, I would name it preprocessor, but that's a question of taste.

Great, I'll add that then.

> Something else to consider: How shall the mapping rule be defined?
> We could write
> {% addtoblock "css" %}<link href="{% static %}css/my-style.scss" rel="stylesheet" type="text/x-scss" />{% endaddtoblock %}
> and use text/x-scss as the key for applying a rule, or we could write
> {% addtoblock "scss" %}<link href="{% static %}css/my-style.scss" rel="stylesheet" type="text/css" />{% endaddtoblock %}
> and use scss as the key for applying a rule.

As with the ``render_block`` postprocessor, I won't actually implement any pre/post-processors in sekizai, so this is really up to the implementation.

**Comment by ojii** [comment]
Upgrade sekizai to 0.8.1 or higher to get ``preprocessor`` in ``addtoblock``.

**Comment by jrief** [comment]
> As with the render_block postprocessor, I won't actually implement any pre/post-processors in sekizai, so this is really up to the implementation.

Sure, that's much better. And it keeps the template tags symmetrical! Use postprocessor in ``{% render_block ... %}`` and preprocessor in ``{% addtoblock ... %}``.
