### ISSUE TITLE
Cache cms placeholder with plugins that use sekizai

### ISSUE THREAD

**Issue by darbula** [ojii/django-sekizai#45]
This is more a feature request or question than an issue.

In template:

```
{% cache 100 footer %}
  {% static_placeholder "footer" %}
{% endcache %}
```

If CMS plugin in placeholder `footer` uses sekizai then its sekizai content is not cached. Im aware of the `Watcher` that can help to catch changes in the context and set and restore sekizai data from cache, but it would be nice if it could be done just from template?

**Comment by ojii** [comment]
I assume you are aware that ``static_placeholder`` already caches by default. The issue here is really detecting if sekizai needs to cache things or not, so the solution would be writing a tag ``cache_with_sekizai`` that does the same that ``cache`` does but is sekizai aware.

**Comment by darbula** [comment]
Yes I'm aware that placeholders are cached by default but some of my placeholders must be excluded from caching thus I have set caching of placeholders to False and now I'm looking for a way to cache only those that can be cached i.e. footer.

It would be nice if placeholders caching could be controlled with more granularity, for example through `CMS_PLACEHOLDER_CONF`.

Also better explanation of how `CMS_PAGE_CACHE`, `CMS_PLACEHOLDER_CACHE`, and `CMS_PLUGIN_CACHE` work and correlate would be beneficial as noted [here](https://github.com/divio/django-cms/issues/3961).

**Comment by ojii** [comment]
> It would be nice if placeholders caching could be controlled with more granularity, for example through CMS_PLACEHOLDER_CONF.
> 
> Also better explanation on how CMS_PAGE_CACHE, CMS_PLACEHOLDER_CACHE, and CMS_PLUGIN_CACHE work and correlate would be beneficial as noted here.

please report this to divio/django-cms, thanks.

**Comment by darbula** [comment]
I have reported both. If the suggested tag should be part of django-sekizai then this issue could remain open?

**Comment by ojii** [comment]
This was fixed in https://github.com/divio/django-cms/pull/2887 (and 0.8.2)
