### ISSUE TITLE
Older version published as 0.8.1

### ISSUE THREAD

**Issue by tiberiuana** [ojii/django-sekizai#46]
It looks like the version published as 0.8.1 is in fact an older one and doesn't match the 0.8.1 tag on GitHub. 

To replicate: use `{% sekizai_tags %}` in a Django 1.8 app.
This results in:
`TemplateSyntaxError: 'sekizai_tags' is not a valid tag library: ImportError raised loading sekizai.templatetags.sekizai_tags: cannot import name VariableNode`

The fixes for Django 1.8 compatibility (in 0.8.1) are not present in what pip installs as 0.8.1.

**Comment by xpanta** [comment]
just go to 

~/.virtualenvs/<YOUR_PROJECT>/lib/python2.7/site-packages/sekizai/helpers.py

and change this:
from django.template import VariableNode, Variable

to this:
from django.template.base import VariableNode, Variable

It worked for me.

**Comment by mbrochh** [comment]
Facing the same issue. @ojii any change you could make a proper release to PyPi?

**Comment by Franktian** [comment]
+1

**Comment by justuswilhelm** [comment]
+1

**Comment by razisayyed** [comment]
+1

**Comment by pilat** [comment]
+1

**Comment by redzer101** [comment]
+1

**Comment by biodigitals** [comment]
+1

**Comment by kevingill1966** [comment]
+1

**Comment by Lacrymology** [comment]
+1

**Comment by ojii** [comment]
newest version is 0.8.2
