### ISSUE TITLE
Please release a new version that's compatible with Django 1.8

### ISSUE THREAD

**Issue by badder** [ojii/django-sekizai#47]
The current head of master seems to have fixed Django 1.8 compatibility, but it's not available on pip yet. What's the plan for the release? Thanks!

**Comment by badder** [comment]
Actually, testing on Django 1.8, looks like sekizai fails silently (not rendering blocks at all).

**Comment by mbi** [comment]
@badder in the meantime you can `pip install https://github.com/ojii/django-sekizai/archive/master.zip`, but I agree: an official release supporting Django 1.8 would be much appreciated.

**Comment by jokerejoker** [comment]
+1

**Comment by phpcitizen** [comment]
Yes, lost hours to find out this was the issue... please update pip. Thanks for the great work.

**Comment by biggosh** [comment]
+1 
sekizai is very usefull. so please update pip repository tagging last version on github. thx

**Comment by benjaoming** [comment]
+1

@ojii :)

**Comment by gst** [comment]
+1 ;)

**Comment by razisayyed** [comment]
+1

**Comment by Franktian** [comment]
+1

**Comment by anvio** [comment]
+1

**Comment by benzkji** [comment]
+1

**Comment by ojii** [comment]
0.8.2 compatible with 1.8 has been out for a few days now.
