### ISSUE TITLE
Usage clarification

### ISSUE THREAD

**Issue by prologic** [ojii/django-sekizai#50]
Could you please clarify:

> Use one of the following:
> * Put sekizai.context_processors.sekizai into your TEMPLATE_CONTEXT_PROCESSORS setting and > use django.template.RequestContext when rendering your templates.
> * Use sekizai.context.SekizaiContext when rendering your templates.

Is this an "or" use here? Do one or the other?

**Comment by ojii** [comment]
fixed in 50d5a23
