### ISSUE TITLE
django.utils.importlib deprecation warnings

### ISSUE THREAD

**Issue by timgraham** [ojii/django-sekizai#51]
`from django.utils.importlib import import_module` is deprecated (removed in Django 1.9). If you don't mind dropping Python 2.6 support, we can replace it with `from importlib import import_module`.

**Comment by ojii** [comment]
I don't mind dropping Python 2 (.6) support at all, but I guess our friends over at divio/django-cms won't like that too much. Will move to ``importlib`` though. Thanks for reporting

**Comment by ojii** [comment]
closed in bb3992e06339006bea67ebb37daf5992f11a0600
