### ISSUE TITLE
RemovedInDjango19Warning in django 1.8

### ISSUE THREAD

**Issue by jproffitt** [ojii/django-sekizai#53]
The warning comes from `sekizai/templatetags/sekizai_tags.py`, line 6:

    RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.

**Comment by jproffitt** [comment]
Sorry, I just noticed this was fixed in https://github.com/ojii/django-sekizai/commit/bb3992e06339006bea67ebb37daf5992f11a0600, but it has not been released to pypi yet,

**Comment by FinalAngel** [comment]
@ojii would you be able to create a new release?
