### ISSUE TITLE
Add runtests.py to release tarballs

### ISSUE THREAD

**Issue by Elizafox** [ojii/django-sekizai#59]
For distribution QA reasons (especially at Gentoo) it would be helpful to include runtests.py to make it easy to run the tests.

**Comment by ojii** [comment]
Interesting. The problem with that is, it would end up in the global python 'namespace' as far as I know, so I don't think it could just be included as-is.

Could you just use a tarball from github (as opposed to one from pypi)?

**Comment by vstoykov** [comment]
I think that there is a way to put stuff in source distribution but not in `site-pakages` and binary distributions.

I'm not sure if you install the package directly from github (and not from source distribution) what will happens.

**Comment by ojii** [comment]
I guess I could simply turn it into a script that gets installed alongside sekizai. So you'd do `python setup.py install` (or `develop`), then `run-sekizai-tests` or whatever I would name it. @Elizafox would that be an acceptable solution for your use case?

**Comment by ojii** [comment]
closed because there was no follow up on this
