### ISSUE TITLE
Please don’t update installed django 

### ISSUE THREAD

**Issue by robslotboom** [ojii/django-sekizai#60]
Since Django 1.9 has many changes not supported yet by other projects/modules.
Please don’t (pip) upgrade django if 1.8 is already installed.

**Comment by ojii** [comment]
This is not a sekizai issue at all, but rather a pip feature/issue.

You should use a requirements file in your project with all package versions pinned, so you don't accidentally upgrade packages. See https://pip.pypa.io/en/stable/ for more information.
