### ISSUE TITLE
render_to_string

### ISSUE THREAD

**Issue by Eraldo** [ojii/django-sekizai#61]
How can I add css to my header when rendering something to a string that later gets displayed on a template that inherits from base.

Here it would make sense that only at then end when the base template is rendered it also grabs all addtoblock elements and pulls them into the header or something like that.

What do you think? Or do you have alternative ideas on how to handle it?

**Comment by ojii** [comment]
I'm not sure I understand what you're trying to do.

Is this what you're doing (semi-pseudocode)?

```python

def foo():
    context1 = SekizaiContext()
    output = render_to_string('template1.html', context1)
    context2 = SekizaiContext({
        'output': output
    })
    return render_to_string('tempalte2.html', context2)
```

```django
{# template1.html #}
{% addtoblock "css" %}hoge{% endaddtoblock %}
```

```django
{# template2.html #}
{% render_block "css" %}
{{ output|safe }}
```

**Comment by Eraldo** [comment]
Close..
Difference: Imagine that foo being a template tag that does only use (render) `template1`.

Example:
```python
@register.simple_tag(takes_context=True)
def label(context, label=None, **kwargs):
    label = label or context.get('label', {})
    label_context = label
    label_context.update(kwargs)
    label_template = 'atoms/label.html'
    return render_to_string(label_template, context=label_context)
```

So.. the difference is that label (template tag) only renders its template.
And I call the template tag in my main template somewhere.
The mein sekizai block tags are in the main template.

Does it make sense now?

**Comment by ojii** [comment]
sekizai cannot work if you isolate the context. You can however manually pass it:

```python
from sekizai.helpers import get_varname

@register.simple_tag(takes_context=True)
def label(context, label=None, **kwargs):
    label = label or context.get('label', {})
    label_context = label
    label_context.update(kwargs)
    label_context[get_varname()] = context[get_varname()] # inherit sekizai context
    label_template = 'atoms/label.html'
    return render_to_string(label_template, context=label_context)
```

**Comment by ojii** [comment]
Closing this as my last comment should explain how to do this.

**Comment by Eraldo** [comment]
Yes that explains it -- thank you @ojii. :)
