### ISSUE TITLE
Compatability with Django 1.10

### ISSUE THREAD

**Issue by JonasGroeger** [ojii/django-sekizai#65]
Hi!

I have a Django App that users Django 1.10. I tried to use `django-sekizai` (in version 0.9.0 but it did not work. This happens when trying `{% load sekizai_tags %}`:

```
TemplateSyntaxError at /
'sekizai_tags' is not a registered tag library. Must be one of:
cache
future
i18n
l10n
static
staticfiles
tz
```

The relevant section in my configuration looks like this:
```
# TEMPLATE CONFIGURATION
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            str(PROJECT_ROOT.path('templates')),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
            ],
        },
    },
]
```

Somehow the context processor is not registered?

**Comment by ojii** [comment]
Hi. django-sekizai does not support 1.10 yet. I will be at a PyCon this weekend and hopefully will have some time to look into this.

**Comment by trumpet2012** [comment]
@JonasGroeger I don't think this particular issue is because of Django 1.10 support. Sekizai works normally on django 1.10. It only breaks for 1.10 when it cannot find the Sekizai context variable.

Double check and make sure you have `sekizai` listed in your `INSTALLED_APPS`.

**Comment by ojii** [comment]
since there was no update on this in quite a while, I'm closing this.

**Comment by webyneter** [comment]
Any news on that?
