### ISSUE TITLE
Issue rendering addtoblock with SCSS in AWS S3

### ISSUE THREAD

**Issue by jamsheer** [ojii/django-sekizai#69]
```django
{% render_block 'css' postprocessor 'compressor.contrib.sekizai.compress' %}
    {% addtoblock 'css' %}
<style type="text/x-scss">
            @import 'app_static/scss/_mixin.scss';
            @import 'app_static/scss/_variable.scss';
            @import 'app_static/scss/_mobile.scss';
 </style>

{% endaddtoblock %}
```

The above code not rendering properly for the first load and when ever cached css file missing

**Comment by ojii** [comment]
The code above is nowhere near enough to reproduce this. Also it's not really clear what is "not working", could you please provide a way to reproduce this and clearly state what you expect to happen and what happens instead?

**Comment by jamsheer** [comment]
I am importing the css this way. Where the first css is being loaded from CDN and the latter is from the local path

{% addtoblock 'css' %}
    <link rel="stylesheet" type="text/css" href="https://cd.example.com/css/main.css">
    <style type="text/x-scss">
        @import 'app_static/scss/_mixin.scss';
        @import 'app_static/scss/_variable.scss';
        @import 'app_static/scss/_mobile.scss';
    </style>
{% endaddtoblock %}


On 1st page load, Only xscss are being processed and saved in S3, But on the rendered html source it shows as below

<link rel="stylesheet" type="text/css" href="https://cd.example.com/css/main.css">
<style type="text/x-scss">
    @import 'app_static/scss/_mixin.scss';
    @import 'app_static/scss/_variable.scss';
    @import 'app_static/scss/_mobile.scss';
</style>

The addtoblock has not being able to create one single CSS file with all of the CSS & SCSS. 

Again when i refresh the page, this time the S3 includes both of the CSS & SCSS and even the rendered HTML includes the once CDN css file.

**Comment by ojii** [comment]
I'm sorry, but this is not enough to reproduce this issue for me. Please create a project on github (or a gist), or anywhere you chose which includes all I need (besides S3, I have access to that) to see what's happening. Please include instructions on how to setup (a requirements.txt and a python version will be fine) and how to run it. 

From a quick glance, it sounds like the issue might be with compressor, not sekizai. However having never used compressor and not knowing how to reproduce this, I cannot say this for sure.

**Comment by jamsheer** [comment]
Sorry , It was a permission issue with static folder , Now its working properly , Thanks for your support
