### ISSUE TITLE
Why don't you implement that placed rander_block inside tempate tag?

### ISSUE THREAD

**Issue by FavorMylikes** [ojii/django-sekizai#70]
{% render_block %} tags must not be placed inside a template tag block (a template tag which has an end tag, such as {% block %}...{% endblock %} or {% if %}...{% endif %}).

I can't use extend adminlte.html at my base page.

**Comment by FavorMylikes** [comment]
Is that hard for some reason you can't implement ? or what should I do?

**Comment by ojii** [comment]
Hi FavorMylikes. Unfortunately, that restriction is a restriction of the Django template engine itself. Please browse through the old issues here on github for more information and potential workarounds.
